### ISSUE TITLE
No storage class seems to exist in the PVC

### ISSUE THREAD

**Issue by jayunit100** [cetic/helm-nifi#10]
**Describe the bug**

No storage class seems to exist in the PVC

**Version of Helm and Kubernetes**:

```
[centos@jay-apachecon2019 ms-spark]$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
[centos@jay-apachecon2019 ms-spark]$ kubectl get vdersion
error: the server doesn't have a resource type "vdersion"
[centos@jay-apachecon2019 ms-spark]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
[centos@jay-apachecon2019 ms-spark]$ 

```
**What happened**:

Looks like my PVCs are created but they dont define a StorageClass.  I assume thats not intentional ? 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2019-08-24T13:01:30Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: zookeeper
    component: server
    release: nifi
  name: data-nifi-zookeeper-0
  namespace: bigdata
  resourceVersion: "188873"
  selfLink: /api/v1/namespaces/bigdata/persistentvolumeclaims/data-nifi-zookeeper-0
  uid: 39728f4c-82d7-4627-a9c6-4e19961986d4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
status:
  phase: Pending
```                           

**What you expected to happen**:

My PVC would have an explicit storageClassName, that i could fulfill.  

**How to reproduce it** (as minimally and precisely as possible):

`helm install --name nifi cetic/nifi --namespace=bd --set persistence.storageClass=default --set storageClass=default2` has no effect, i.e. you 
dont see the `storageClassName` in `kubectl get pvc -n bd`

**Anything else we need to know**:

I guess one option as a workaorund would be to just use `default` storage classes for everything.

**Comment by alexnuttinck** [comment]
Hello @jayunit100, thanks for the report, I will look into it in the next days.

**Comment by mjschmidt** [comment]
If no storage class is selected kubernetes default is to pick whatever the default storage class is. If no default storage class is set, it will pick default. So there is probably nothing providing kubernetes storage? How did you deploy kubernetes? Was it minikube or something else?

**Comment by mjschmidt** [comment]
What is the output of
'kubectl get storageclass' 
'kubectl get pv'
'kubectl get pvc'

**Comment by alexnuttinck** [comment]
As there is no answer from @jayunit100, I close this issue. @jayunit100, don't hesitate to reopen this issue if there is a need to.
