### ISSUE TITLE
[cetic/nifi] Calling `helm dep up`  when installing chart from local clone fails

### ISSUE THREAD

**Issue by raghav1uphealth** [cetic/helm-nifi#100]
**Describe the bug**
When cloning the repo and trying to call `helm dependency update`, get the following error:
```
Getting updates for unmanaged Helm repositories...
Error: could not find protocol handler for:
```
It looks like helm doesn't like that no repository is specified for `ca` in Chart.yml dependencies, even though the subchart is already in `charts/`. Commenting out the `ca` dependency and then calling `helm dependency update` will allow the other dependencies to be downloaded into `charts/`.

**Version of Helm and Kubernetes**:
Helm Version: v3.4.0

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Follow the install steps:
```
git clone https://github.com/cetic/helm-nifi.git nifi
cd nifi
helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
helm repo update
helm dep up
```

**Anything else we need to know**:
Simply installing the helm chart via `helm install my-release cetic/nifi` works fine, but I'm looking to customize the chart.

**Comment by sushilkm** [comment]
This is a bug on helm 3.4.0
Try downgrading the helm or wait for the new release probably late next week.
https://github.com/helm/helm/issues/8940

**Comment by raghav1uphealth** [comment]
Thank you, I'll try that! I'm new to helm, didn't consider helm itself having an issue. Closing this.

**Comment by sushilkm** [comment]
Another thing that you can do is use `--skip-refresh`
```
helm dep up --skip-refresh
```
