### ISSUE TITLE
[cetic/nifi] Deployment on microk8s with already deployed zookeeper

### ISSUE THREAD

**Issue by MLNW** [cetic/helm-nifi#102]
**Describe the bug**
I am trying to deploy this chart on a microk8s cluster already running a bitnami/zookeeper chart. The first issue I had was that when leaving the nifi registry enabled a zookeeper pod would be created by this chart even though Zookeeper was disabled in the values.

After disabling the nifi registry as well as the zookeeper and supplying the FQDN of the already deployed Zookeeper it seems like that parts of the chart deploy fine but I am not able to connect to the HMI.

The Kubernetes dashboard also marks the nifi release in an error state. When clicking on it it says:  
```
Liveness probe failed: dial tcp 10.1.144.201:8080: connect: connection refused
```

I am using LoadBalancer with metallb if that makes any difference.

**Version of Helm and Kubernetes**:
- Helm: v3.0.2
- Kubernetes: microk8s  v1.19.2

**What happened**:
The liveness probe fails and the HMI is not available

**What you expected to happen**:
The liveness probe succeeds and the HMI is available.

**How to reproduce it** (as minimally and precisely as possible):
1. Stand up a microk8s installation in WSL2 with dns, dashboard, helm3, storage and metallb enabled.
1. Deploy bitnami/zookeeper.
1. Install this chart with the values below.

**Anything else we need to know**:

[bitnami-zookeeper.txt](https://github.com/cetic/helm-nifi/files/5505158/bitnami-zookeeper.txt)
[cetic-nifi.txt](https://github.com/cetic/helm-nifi/files/5505156/cetic-nifi.txt)

I have verified that Zookeeper is deployed correctly by deploying bitnami/kafka, connecting to the deployed zookeeper and sending/receiving messages.

**Comment by MLNW** [comment]
Any idea what the problem could be?

**Comment by tunaman** [comment]
We have a somewhat similar setup in that we deploy on a Rancher (2.5.5) cluster with Zookeeper installed in it's own namespace, we use the zookeeper svc url in the nifi config to connect to that cluster and it works fine. Hope this helps.

```yaml
zookeeper:
  enabled: false
  port: 2181
  replicaCount: 3
  url: zk-zookeeper.zookeeper.svc.cluster.local
```

**Comment by weltonrodrigo** [comment]
I confirm the chart deploys fine without preexistent zookeeper just by indicating the url.
