### ISSUE TITLE
Cluster disconnected

### ISSUE THREAD

**Issue by vikashsingh009** [cetic/helm-nifi#104]
I  have used  helm  chart  to  migrate  to nifi  1.12 where  i  have  replaced  flow.xml.gz  in  side  data  folder  with  flow.xml.gz  with 1.11 ,nifi  server  started  but  after  some  time  in  the  ui  getting  below  error 
Cluster Connection
This node is currently not connected to the cluster. Any modifications to the data flow made here will not replicate across the cluster.

i  am  attaching  here  logs  and  screen-shots

![image_2020_11_24T11_48_53_004Z](https://user-images.githubusercontent.com/7962189/100090578-5eb87700-2e79-11eb-90b7-d07d31fd8fd8.png)

[app-log.log](https://github.com/cetic/helm-nifi/files/5589575/app-log.log)

**Comment by banzo** [comment]
Please provide more information: kubernetes version, deployment details, values.yaml, etc.
