### ISSUE TITLE
[cetic/nifi] Support Nifi-Registry GitFlowPersistenceProvider

### ISSUE THREAD

**Issue by jdesroch** [cetic/helm-nifi#109]
Support versioned flows stored in a git repo that NiFi Registry can use with the GitFlowPersistenceProvider.

**Describe the solution you'd like**
Use latest nifi-registry chart that has git configuration implemented.  https://github.com/dysnix/charts version **0.2.1**

**Additional context**
The dyxnix chart was recently updated to allow ssh configuration required for git clone.

**Comment by thilko** [comment]
We appreciate the support of the GitFlowPersistenceProvider! Could you give a rough estimate when the change will be merged to master?

**Comment by tunaman** [comment]
this issue might be fixed by [the following PR](https://github.com/cetic/helm-nifi/pull/142)
