### ISSUE TITLE
Problem with upgrade

### ISSUE THREAD

**Issue by JHC88** [cetic/helm-nifi#11]
```
[root@virt_dev1 gohttpserver]# helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
[root@virt_dev1 gohttpserver]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
I have some troubles when I try to do upgrade like this:
```
helm upgrade helm-nifi -f values.yaml .
```
I get the following error:
```
UPGRADE FAILED
ROLLING BACK
Error: failed to create resource: the server could not find the requested resource
Error: UPGRADE FAILED: failed to create resource: the server could not find the requested resource
```

But, if I run:
```
helm upgrade helm-nifi -f values.yaml . --debug --dry-run
```
I get this message:
```
Release "helm-nifi" has been upgraded. Happy Helming!
LAST DEPLOYED: Sun Aug 25 14:42:45 2019
```
Can you help me and point me where is my mistake? Thank for advance!

P.S. If I do helm ```delete --purge helm-nifi``` and do ``` helm install cetic/nifi -f values.yaml --namespace $NAMESPACE --name $RELEASE_NAME``` - all is ok.

**Comment by alexnuttinck** [comment]
Hello @JHC88,

Is it possible that your first installation failed and then you tried to make an upgrade? As explained in https://github.com/helm/helm/issues/3353

I can't reproduce the error.

**Comment by JHC88** [comment]
> Hello @JHC88,
> 
> Is it possible that your first installation failed and then you tried to make an upgrade? As explained in [helm/helm#3353](https://github.com/helm/helm/issues/3353)
> 
> I can't reproduce the error.

Great Thank! This info helped to me!
