### ISSUE TITLE
Question about scaling

### ISSUE THREAD

**Issue by tylux** [cetic/helm-nifi#12]
In the README there is mention that replicaCount > 1 is unstable, what does `unstable` mean and are there plans to fix it?

**Comment by lhb008** [comment]
I have tried when replicaCount > 1, but cluster failed to start. I have the same question with @tylux ,is there any plans to fix this or give some guidence.

**Comment by alexnuttinck** [comment]
repreplicaCount > 1 is now fixed, thanks to @lhb008, #13. I close this issue.
