### ISSUE TITLE
Is there a plan to bump the version of nifi-registry?

### ISSUE THREAD

**Issue by murphyki** [cetic/helm-nifi#123]
Hi,
Just wondering if there is any plan to bump the version of nifi-registry that is currently used from v0.1.1 to v0.2.1?
I'm asking because in v0.1.1 of the nifi-registry helm chart the helm test is broken but seems to be fixed in v0.2.1.
Thanks,
Kieran

**Comment by banzo** [comment]
We need to see what the impact is, would you be ok to propose a pull request?

**Comment by murphyki** [comment]
Hi @banzo,
Sure, I'll propose a pull request.
Thanks,
Kieran

**Comment by tunaman** [comment]
@murphyki Are you still planning on making a PR for this issue? We are looking at replacing the registry we have now and really want to go for version `0.8.0`. We already [opened an issue ](https://github.com/dysnix/charts/issues/19) for that.

**Comment by murphyki** [comment]
@tunaman I had intended to make a PR for this but apologies, I never got it. Will I hold off now since ye will be moving to 0.8.0?

**Comment by tunaman** [comment]
Yeah you could wait until we have a reply on that open issue unless you need it like right now :)

**Comment by a-nldisr** [comment]
Opened another ticket on their side with the request to add a License. Since this chart uses their chart for the nifi registry and they do not have a License attached what is your idea about this?

**Comment by a-nldisr** [comment]
License issue is fixed.

**Comment by a-nldisr** [comment]
The moment https://github.com/dysnix/charts/issues/19 is merged I will make a PR here.

**Comment by a-nldisr** [comment]
PR made, see #142

**Comment by banzo** [comment]
Thank you! I think we can close this issue, and maybe #109 ?
