### ISSUE TITLE
[cetic/nifi] Error: no repositories found. You must add one before updating

### ISSUE THREAD

**Issue by patsevanton** [cetic/helm-nifi#124]
Hello! Thanks for helm nifi

```
git clone https://github.com/cetic/helm-nifi.git nifi
cd nifi
helm repo update
```
Error
```
Error: no repositories found. You must add one before updating
```

**Comment by banzo** [comment]
With Helm 3 you need to add the stable repo manually:

```
helm repo add stable https://charts.helm.sh/stable
```

Can you confirm this fixes your issue so we update the documentation README.

Ref: https://stackoverflow.com/questions/57970255/helm-v3-cannot-find-the-official-repo

**Comment by alexnuttinck** [comment]
Yes, if you want to run the nifi helm chart locally, you must add the nifi dependencies: 

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add dysnix https://dysnix.github.io/charts/
```

I will add this to the README.

Otherwise you can use the cetic helm chart to run nifi: https://github.com/cetic/helm-nifi#add-helm-repository

**Comment by patsevanton** [comment]
I check this instruction. It works.

```
git clone https://github.com/cetic/helm-nifi.git nifi
cd nifi
helm dep up
helm install --set replicaCount=1,persistence.enabled=true,service.type=LoadBalancer,ingress.enabled=true,ingress.hosts[0]=nifi.192.168.22.7.xip.io nifi ./
```

**Comment by alexnuttinck** [comment]
Ok, we can close this issue.
