### ISSUE TITLE
[cetic/nifi] CrashLoopBackOff for nifi-0 3/4 Server is failing to spin up

### ISSUE THREAD

**Issue by carlosxmunoz** [cetic/helm-nifi#130]
**Describe the bug**
The nifi-0 pod is stuck in CrashLoopBackOff
![image](https://user-images.githubusercontent.com/52302029/110727549-1da66180-81e1-11eb-8a14-e9aaf2784b68.png)
![image](https://user-images.githubusercontent.com/52302029/110727563-24cd6f80-81e1-11eb-805b-b90467058213.png)
![image](https://user-images.githubusercontent.com/52302029/110727579-28f98d00-81e1-11eb-900e-069a60dbd82a.png)

**Version of Helm and Kubernetes**:
Helm v3.5.0
Kubernetes Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**What happened**: Pulled down the source code from the cetic/helm-nifi repo. Modified line 12 in the configmap.yaml as follows `{{ (.Files.Glob "configs/*").AsConfig | indent 2 }}`

In the bootstrap.conf changed "run.as=" to "run.as=nifi"

**What you expected to happen**: For the nifi-pod not to crash

**How to reproduce it** (as minimally and precisely as possible):
Pull down the source code from the cetic/helm-nifi repo. Modified line 12 in the configmap.yaml as follows `{{ (.Files.Glob "configs/*").AsConfig | indent 2 }}`

In the bootstrap.conf changed "run.as=" to "run.as=nifi"

helm install nifi ./

**Anything else we need to know**: Figured out that the "does not exist. Exiting" error from [url](https://community.cloudera.com/t5/Support-Questions/when-tried-to-bring-up-new-NiFi-cluster-received-error-The/td-p/112174). In other words whatever you set run.as= to  will show up when you run kubectl logs nifi-0 server

**Comment by aixiansheng** [comment]
I also can't get the chart started.. the "server" container is failing because the TLS generation tool ran out of space:

kubectl logs nifi-0 -c server

**Comment by a-nldisr** [comment]
Can you share your values.yml?
