### ISSUE TITLE
[cetic/nifi] Nifi Pods Status is Init:0/1 indefinitely 

### ISSUE THREAD

**Issue by Lavanya2102** [cetic/helm-nifi#144]
I am trying to install Nifi on the Kubernetes cluster using cetic/helm-nifi. But once I installed nifi, the pods are not running but are in "status: Init:0/1" indefinitely. 
![Screenshot (9)](https://user-images.githubusercontent.com/43609457/119335701-56b38580-bcaa-11eb-9bba-24ee335f0d71.png)
Then I checked the logs of the containers and the init container zookeeper has been having a problem. It shows bad address. 
<img width="233" alt="bad address" src="https://user-images.githubusercontent.com/43609457/119336025-b0b44b00-bcaa-11eb-9cae-84f0a6146567.PNG">

Due to this issue, the pods aren't running and I'm not able to access Nifi UI. How do I debug this?
 
Version of helm: 3.5.4
Version of Kubernetes Cluster: 1.21.0

**Comment by nuttybrewer** [comment]
```
kubectl describe pod my-release-nifi-0
```
In the events it'll show you why it's failing. Usually it's because it can't mount something or a claim for a persistent volume is broken.

**Comment by Lavanya2102** [comment]
I did check the events and it says none. But the storage class was not set, now I set it on all zookeeper nodes. 
All of them are running, but the nifi node still says init 0/1. what might be the reason?
<img width="393" alt="nifi1" src="https://user-images.githubusercontent.com/43609457/120277231-6ac23d00-c2d1-11eb-9e87-d83531d7a2ca.PNG">

**Comment by deebify** [comment]
I have the same issue with k8s on GCP. Nifi pods in Init state.
Have you solved it?

**Comment by Lavanya2102** [comment]
No, i haven't.

**Comment by banzo** [comment]
Please provide more information. The full output of nuttybrewer's command for example.

Note: I can not reproduce the issue on Minikube, it takes 45 minutes to install with my home internet connection but it gets there in the end.
