### ISSUE TITLE
PS C:\nifi-authentication-test> helm install nifidm cetic/nifi --version=0.7.5 --namespace=test --values=./test_nifi.yaml Error: Service "nifidm" is invalid: spec.ports[0].nodePort: Invalid value: 30236: provided port is already allocated

### ISSUE THREAD

**Issue by Ahbab-Ahmed** [cetic/helm-nifi#149]
Hi Team,

I have already deployed Nifi using this Helm chart in one one the namespace (lets say 'dev' namespace) on kubernetes cluster, but when I am trying to deploy Nifi in another namespace (lets say 'test' namespace) on the same cluster, I am getting the below error 

"PS C:\nifi-authentication-test> helm install nifidm cetic/nifi --version=0.7.5 --namespace=test --values=./test_nifi.yaml
Error: Service "nifidm" is invalid: spec.ports[0].nodePort: Invalid value: 30236: provided port is already allocated".

Can someone please tell how to resolve this issue ?

**Comment by banzo** [comment]
Please provide more information, as requested in the [bug report template](https://github.com/cetic/helm-nifi/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
