### ISSUE TITLE
Keycloak - self-signed certificates not working

### ISSUE THREAD

**Issue by AyadiAmen** [cetic/helm-nifi#153]
**Describe the bug**

When trying to integrate nifi with keycloak, the tls-toolkit generated self signed certs are not working, after configuring nifi and passing the keystore to keycloak, i get the following error when trying to access nifi UI:

```
Ce site ne peut pas fournir de connexion sécurisée 
192.168.64.57 n'a pas accepté votre certificat de connexion, ou vous ne l'avez pas fourni.

Essayez de contacter l'administrateur système.

ERR_BAD_SSL_CLIENT_AUTH_CERT
```
the config for nifi-keycloak integration can be found [here](https://github.com/cetic/helm-nifi/commit/4bb68b3740a8040028e35fec8243510e253c8f65)

the documentation can be found [here](https://github.com/cetic/fadi/blob/featurek/keycloak/doc/keycloak.md) 

A **potential solution** might be providing valid certs instead of generating self signed certs.

**Comment by banzo** [comment]
Linked to #118

**Comment by bmgante** [comment]
Hello, Would like to understand if this issue is the cause of not being able to access nifi UI after trying to enable https and ldap (should be the same for oidc). The error i got when trying to access the ui is:

![image](https://user-images.githubusercontent.com/27358817/123612301-52730e80-d7fa-11eb-9894-7e9c9f990d41.png)

**Comment by zakaria2905** [comment]
Hi,
To fix the self-signed certificates issue, we have to add the generated certificate to the browser.
To do this, we can copy the folder that contain it from the pod with this command:
- kubectl cp <the-nifi-pod>:/opt/nifi/nifi-current/conf/ <your-path>
Then, we have to add the .p12 file to the browser (the password is in the .password file).

**Comment by banzo** [comment]
The question seems answered, there is [additional documentation on KeyCloak integration](https://github.com/cetic/helm-nifi/tree/master/doc) for the new chart version.
