### ISSUE TITLE
Additional libraries in the Nifi containers

### ISSUE THREAD

**Issue by Kumar6295** [cetic/helm-nifi#155]
We are using nifi with helm chart, after created pods we copied files.

Using kubectl cp command copied some nar file to /opt/nifi/nifi-current/lib.

we try to use those processor/nar files in nifi ui. it is giving like is processor name is not known to this NiFi instance.

After copying the files, need to execute any command?

**Comment by banzo** [comment]
You should probably be using mounted volumes instead of manually copying the libs: https://github.com/cetic/helm-nifi#use-custom-processors

**Comment by Kumar6295** [comment]
Thanks for reply.

**Comment by bmgante** [comment]
@Kumar6295 i am having the same problem you had. Would you pls mind to detail a bit how did you overpassed this and share your config?

**Comment by Kumar6295** [comment]
@bmgante 
we are using heketi with glusterfs for volumes.it will create volumes dyanmically.
Added some configuration in value.yaml and stateful.yaml like below
**value.yaml**

## Include aditional processors
  customLibPath: "/opt/nifi/custom-lib"
  storageClass: glusterfs

# Storage capacity for the CustomFile repository
  customLibStorage:
    size: 500Mi

**stateful.yaml**
under   volumeMounts:
                    - name: "custom-lib"
                      mountPath: /opt/nifi/custom-lib
under volumeClaimTemplates:
    - metadata:
        name: custom-lib
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.customLibStorage.size }}

mountpath and customLibPath should be same and name of volumeClaimTemplates and volumeMounts names should be same.
Once above configuration is done. use helm to install .it will create dynamic volume for mentioned path then you can use for lib or anything.
