### ISSUE TITLE
[cetic/nifi] question - forwarding to 8080, connection refused

### ISSUE THREAD

**Issue by ecl996** [cetic/helm-nifi#187]
Hello,

I did a default installation of this chart and setup a port-forward to 8080, when I try to access http://localhost:8080/nifi I get an empty response and I can see that my port-forward says that the connection was refused. It appears from the nifi logs that everything is running correctly. Is there another setting I need to change to enable this?

**Comment by banzo** [comment]
does this comment help? https://github.com/cetic/helm-nifi/pull/169#discussion_r716947725

**Comment by ecl996** [comment]
Ah yes all set now! It wasn't the comment per say, for some reason I must have had an older chart. I thought I did a helm update but I must not have. Running the latest nifi chart now with 1.14.0 and https. All set, thank you!
