### ISSUE TITLE
http>>>https --  Mixed Content

### ISSUE THREAD

**Issue by yossisht9876** [cetic/helm-nifi#197]
At the moment NiFi works and I can access it via the ingress host.

look like a Mixed Content issue - some of the "urls" are still in http and nifi is on https so i get  "Mixed Content" error

The problem is that I can't configure any processor at all. Every time, when I click on "configure" I get this error:

Unable to communicate with NiFi
Please ensure the application is running and check the logs for any errors.

error logs on the browser show:

The page at 'https://nifi-xxxx.como/nifi/?processGroupId=root&componentIds=471557be-017d-1000-5ab8-8e8a5dea2994' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://https/nifi-api/provenance/47e447d8-017d-1000-6a48-56f3ac07539e'. 

This request has been blocked; the content must be served over HTTPS.

any idea's ? thanks
@banzo

**Comment by murilolobato** [comment]
I'm facing the same problem, even when using the oficial docker image alone.
