### ISSUE TITLE
[cetic/nifi] Can't create cluster with helm charts

### ISSUE THREAD

**Issue by thanhhaiduong** [cetic/helm-nifi#200]
Hell, 
I want create cluster with helm charts, but I get error.
somebody helm me?

**Comment by thanhhaiduong** [comment]
I want setup 3 pod nifi with helm chart on k8s. I want authen with Singeruser.
But I can't see cluster on nifi even though set properties with isNode: true.
how?

**Comment by thanhhaiduong** [comment]
![image](https://user-images.githubusercontent.com/72290204/143980061-795bfe90-7bc3-4649-8910-c53aba4b0da3.png)
My logs: [Process Cluster Protocol Request-18] o.a.n.c.p.impl.SocketProtocolListener Failed processing protocol message from nifi-1.nifi-headless.nifi.svc.cluster.local due to Received fatal alert: certificate_unknown

**Comment by ElfoLiNk** [comment]
Does anyone knows why this is happening?

![Screenshot 2021-12-06 at 16 23 01](https://user-images.githubusercontent.com/1236551/144872920-5d5808db-e27e-4ddc-8313-6af75fa77e37.png)

**Comment by OlehKovalchyn** [comment]
@ElfoLiNk it's via LDAP? Describe please how you deploy nifi and which components did you use.

**Comment by ElfoLiNk** [comment]
Hi @OlehKovalchyn i'm deploying it with the helm chart with traefik as ingress and keycloak oidc

**Comment by leshibily** [comment]
@ElfoLiNk  can we have a Nifi cluster when the auth is singleUser?

**Comment by shuhaib3** [comment]
@thanhhaiduong were you able to fix this issue.

**Comment by thanhhaiduong** [comment]
> @thanhhaiduong were you able to fix this issue.

not yet, can you help me?

**Comment by mbaron2** [comment]
Hello @thanhhaiduong ,
Could wou give some details of your implementation ? I would create a nifi cluster with this helm but it's doesn't work.

Thanks
