### ISSUE TITLE
NiFi 1.14 is not enabling cluster

### ISSUE THREAD

**Issue by erorci** [cetic/helm-nifi#209]
Hello all, 

I have been trying to deploy on a new k8s cluster and I only get the nodes working as single mode, the cluster option is not enabled in Nifi. Also when checking the NiFi properties it shows isNode false.

Any idea what needs to be changed?

Kind regards,

Emerson

**Comment by weltonrodrigo** [comment]
Can someone confirm which commit introduced this?

I really need to work in a cluster. Does someone knows a workaround?

**Comment by lfreinag** [comment]
I don't know if this helps but I modified the nifi.properties:

```
nifi.cluster.is.node={{.Values.properties.isNode}}
nifi.cluster.flow.election.max.candidates={{.Values.properties.maxCandidates}}
nifi.zookeeper.connect.string={{.Values.properties.zookeeperConnectString}}
```

And on my values.yaml file I have:

```
isNode: true
maxCandidates: 1
zookeeperConnectString: "nifi-zookeeper-1.nifi-zookeeper.nifi-cluster.svc.cluster.local:2181,nifi-zookeeper-2.nifi-zookeeper.nifi-cluster.svc.cluster.local:2181"
```

The Connection String obeys the following format: <pod_name>.<service-name>.<namespace>.svc.cluster.local:2181

I manage at least to get a cluster with one node running. Still trying to figure out how to add the second node though.

<img width="1872" alt="Screenshot 2022-04-21 at 14 41 27" src="https://user-images.githubusercontent.com/102366278/164460298-dae463bc-eb23-4561-873b-2f330ae0b342.png">
