### ISSUE TITLE
after changes made in  nifi when  container  restart all  data  loss

### ISSUE THREAD

**Issue by vikashsingh009** [cetic/helm-nifi#21]
Hi ,
I  have  used  above  charts for  deploying  on  azure  aks ,i  have  enabled persistance .after  that  i  have  created  some  processor  in  nifi  and  killed  and  restart pods ...
when  nifi  get  up i  have lossed all  Processor  which  i  have  created earlier  .
![image](https://user-images.githubusercontent.com/7962189/68753145-84862b80-062a-11ea-97e4-6f0af032631b.png)

i  have  following  question  here  
1) why  each  time  pvc  is  created like  above  example
2)  I  have  some 3rd Party  custom  nar  where  i  need  put  a d

**Comment by vikashsingh009** [comment]
I having Azure Kubernate  Service of  1  node ,i  have chnaged values.yml  persistence:
  enabled: true  ,then hit  this  command 
helm install --wait .  after  that  3  instance  of  zookeeper  and  1 instance  of apache  nifi running  ..
I  have  access  nifi  gui  using  LoadBalncer  IP and  dropped 1  Proceesor to  check  Persistance  working ..

after  that i  have  Killed  Helm  chart  with 
helm  delete --purge <chart  name>
again i  have  fired  this  command helm install --wait ,after  some  time  nifi gui  is  like  a  black  Processor ,mine  Previous  chnages  was  not  reflecting ...

**Comment by vikashsingh009** [comment]
How  to  use  existingClaim for  Persitance ,each  time when  Pods  restarting it  gives  diffrent  storage so  after  terminate i  lost  my  changes

**Comment by vikashsingh009** [comment]
@banzo can  you  please  guide  how  to make Persistance  PVC to  create  only  once not  every  time whenever  Pods terminate  and  create so  that data  will  not  lose

**Comment by vikashsingh009** [comment]
I  have  also  tried  below  steps
1)  created pvc  manual in  azure
2) changed statfull set  file like  this
        volumeMounts:
        - name: logs
          mountPath: /var/log
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: flowfile-repository
        persistentVolumeClaim:
          claimName: flowfile-repository
      - name: content-repository
        persistentVolumeClaim:
          claimName: content-repository
      - name: provenance-repository
        persistentVolumeClaim:
          claimName: provenance-repository
      - name: logs
        persistentVolumeClaim:
          claimName: logs

where  clame name  is already  created  pvc name  
3) all  pods  running  no  error but not  able  to  access  nifi  gui
![image](https://user-images.githubusercontent.com/7962189/68844459-d5138c80-06ef-11ea-9e1a-40bda96bcfbd.png)

**Comment by octopyth** [comment]
Hi @vikashsingh009 , I am also running the helm chart in Azure, I managed to test the viability of the persistency by only changing values.yaml:
`persistence:
   enabled: true`
After you start for the first time and create a sample processor, use the following code to restart the containers:
`kubectl delete pod nifi-0 -n nifi`
I believe the reason you lose your pvc is because you delete the helm chart with --purge. If you want to simulate a pod restart, then I believe it is already working.

**Comment by vikashsingh009** [comment]
Thanks! @octopyth yes  it  works

**Comment by alexnuttinck** [comment]
I close this issue, thanks @octopyth for the answer.
