### ISSUE TITLE
Unable to set "Initial User Identity"

### ISSUE THREAD

**Issue by Sarankrishna** [cetic/helm-nifi#214]
I am trying to set the "Initial User Identity" in authorizers-empty.xml file in the configs folder of my workload. and installed the nifi using the below command. It does not take the authorizers-empty.xml from my local machine as it uses a chart from cetic helm chart repository.  

The file authorizers-empty.xml has john as "initial user identity". I would like to change the initial user identity to something else. Do I need to pull the repository and change the value in authorizers-empty.xml  and publish the helm chart in my own repository to use? 

```
helm install my-release cetic/nifi

**Comment by banzo** [comment]
@Sarankrishna the new version of the chart allow you to set that in the values file, can you confirm?

**Comment by banzo** [comment]
@zakaria2905 we need to update USERMANAGEMENT.md according to the new way things works (authorizers.xml vs authorizers-empty.xml)

**Comment by Sarankrishna** [comment]
@banzo  I am using the branch feature/nifi_1.15.0. I don't find a way to set Initial User Identity in values.yaml file.  I will test with the master branch and let you know.
