### ISSUE TITLE
[cetic/nifi] login-identity-providers-ldap has hardcoded `searchFilter` value

### ISSUE THREAD

**Issue by leokhachatorians** [cetic/helm-nifi#220]
**Describe the bug**
When attempting to pass in a custom `searchFilter`, the config file `login-identity-providers-ldap.xml`  has it currently hard-coded to be `(cn={0})`. This was seemingly changed in https://github.com/cetic/helm-nifi/pull/107. 
 https://github.com/cetic/helm-nifi/blob/cb3f5c09d3389dcfba6d9d595ab80481aa6719f3/configs/login-identity-providers-ldap.xml#L86

**Version of Helm, Kubernetes and the Nifi chart**:
helm 3, k8s 1.2X, nifi chart v1.0.4

**What happened**:
LDAP doesn't work

**What you expected to happen**:
That when passing in a custom `searchFilter` all applicable areas will then have this value set accordingly.

**How to reproduce it** (as minimally and precisely as possible):
Pass in the `searchFilter` value and see that the config doesn't match what you pass in.

**Comment by wielkiborsuk** [comment]
Also 
https://github.com/cetic/helm-nifi/blob/cb3f5c09d3389dcfba6d9d595ab80481aa6719f3/configs/login-identity-providers-ldap.xml#L68
seems hardcoded, even though:
https://github.com/cetic/helm-nifi/blob/ceca5ad379bac51ac18ff383efef6bbfb3eb7ac2/values.yaml#L122
this suggests the strategy is configurable
