### ISSUE TITLE
[cetic/chart] Error: found in requirements.yaml, but missing in charts/ directory: zookeeper

### ISSUE THREAD

**Issue by octopyth** [cetic/helm-nifi#23]
**Describe the bug**
I am attempting to first download the nifi chart and helm install it using the vlues.yaml file:
git clone https://github.com/helm/charts
git clone https://github.com/cetic/helm-nifi
helm install --name nifi --namespace nifi -f helm-nifi/values.yaml helm-nifi
Error: found in requirements.yaml, but missing in charts/ directory: zookeeper

**Version of Helm and Kubernetes**:
irrelevant

**What happened**:
Got error

**What you expected to happen**:
When I attempt to clone the charts folder inside the helm-nifi folder, then I run into other errors.
Can you describe the correct way to download the nifi chart locally and initiate the helm install?

**How to reproduce it** (as minimally and precisely as possible):
git clone https://github.com/helm/charts
git clone https://github.com/cetic/helm-nifi
helm install --name nifi --namespace nifi -f helm-nifi/values.yaml helm-nifi

**Anything else we need to know**:

**Comment by vikashsingh009** [comment]
you   need to first add/update helm  dependency then  only  helm install  command  will  work 
helm dependency update https://kubernetes-charts-incubator.storage.googleapis.com

**Comment by alexnuttinck** [comment]
@octopyth See my answer here: #20

**Comment by octopyth** [comment]
Thanks, for the prompt response. I have created a PR as other helm newbies like me seem to also be struggling with this. Thanks for the great work!
