### ISSUE TITLE
[cetic/nifi] issue title Nifi is deployed successfully. but unable to access nifi UI.

### ISSUE THREAD

**Issue by pawankbh** [cetic/helm-nifi#241]
Nifi is deployed successfully. but unable to access nifi UI.

![image](https://user-images.githubusercontent.com/87305889/156565524-1adeb231-b6a2-474f-b363-cbb8cb485759.png)

**Comment by pawankbh** [comment]
![image](https://user-images.githubusercontent.com/87305889/156565770-9860bd61-af8c-4133-aaf2-007b2f917eda.png)

**Comment by gforeman02** [comment]
@pawankbh try adding `10.124.13.73:8443` (including port) to properties.webProxyHost value.

**Comment by fzhan** [comment]
> @pawankbh try adding `10.124.13.73:8443` (including port) to properties.webProxyHost value.

This should be a dynamic value since a new pod would use a new IP address.

What's the most effective way?
https://community.cloudera.com/t5/Support-Questions/NiFi-1-5-System-Error-Invalid-host-header/td-p/195175

**Comment by fzhan** [comment]
> @pawankbh try adding `10.124.13.73:8443` (including port) to properties.webProxyHost value.

This should be a dynamic value since a new pod would use a new IP address.

What's the most effective way?
https://community.cloudera.com/t5/Support-Questions/NiFi-1-5-System-Error-Invalid-host-header/td-p/195175

**Comment by wknickless** [comment]
@fzhan `properties.webProxyHost` should be set to the name(s) you expect your users to type into their web browser.

For example, see https://github.com/wknickless/helm-nifi/blob/feature/cert-manager/tests/07-oidc-cluster-values.yaml , where `properties.webProxyHost` is set to the DNS name of the Ingress that fronts the NiFi cluster.
