### ISSUE TITLE
[cetic/nifi] Unable to configure authentication for nifi-registry

### ISSUE THREAD

**Issue by pawankbh** [cetic/helm-nifi#249]
I have deployed nifi and nifi registry on kubernetes environment. I have configured nifi with authentication. Could you please let us know how to configure authentication for nifi-registry

**Comment by wknickless** [comment]
Hi @pawankbh you might consider asking that question over at https://github.com/dysnix/charts/tree/main/dysnix/nifi-registry .  That's the upstream for the NiFi Registry chart included in this chart.

But to provide some hope, I focused my time last week finishing off the cert-manager and OIDC NiFi helm chart tests and support so I could turn my attention to ensuring that NiFi Registry also has testable cert-manager, OIDC and SSH-based Git back-end support.  (That's actually my internal organization deliverable.)  I haven't even started writing the tests yet--much less fixing anything in the code that's broken--but if you subscribe to the above repository you should see it when I do.

**Comment by jjjedlicka** [comment]
I am having the same issue.  The configuration seems to go into an authorizers.temp file, but never makes it into the authroizers.xml and thus doesn't work.  Not sure why its doing this or how to get it to push the configuration over to the xml file.

**Comment by wknickless** [comment]
@pawankbh pull request https://github.com/dysnix/charts/pull/199 provides OIDC and Client Certificate authentication support, and includes and end-to-end test with NiFi based on pull request #218 here.

**Comment by wknickless** [comment]
@pawankbh my PR was merged and the official NiFi Registry Helm chart with the fix is available at https://github.com/dysnix/charts/releases/tag/nifi-registry-1.0.0 .
