### ISSUE TITLE
[cetic/helm-nifi] Support NiFi Registry container for flow versioning

### ISSUE THREAD

**Issue by jdesroch** [cetic/helm-nifi#26]
**Is your feature request related to a problem? Please describe.**
I would like to enable NiFi flow version control and allow new NiFi clusters to easily pull in existing flows from other environments.

**Describe the solution you'd like**
Have the option to spin up a [apache/nifi-registry](https://hub.docker.com/r/apache/nifi-registry/) container
- Use the same security/authentication configuration as NiFi
- Configure users/permissions between the applications (proxy, read, write)
- Configure the registry client in the NiFi controller using the [NiFi API ](https://nifi.apache.org/docs/nifi-docs/rest-api/index.html) call to /controller/registry-clients
-  Optionally configure a remote git repo to be cloned on the container and used by the GitFlowPersistenceProvider

**Describe alternatives you've considered**
This could be a separate chart. But the benefit of keeping them together is a single security configuration applied consistently and the potential for no configuration in the NiFi UI before getting started.

**Additional context**
The ultimate goal is to use the NiFi Toolkit and/or NiFi & Registry APIs driven by Kubernetes configuration to allow deployment of a specific version of a NiFi flow developed in a separate environment with no user interaction.

**Comment by alexnuttinck** [comment]
Hello @jdesroch,

Thanks for your feature request! I think it should be really an improvement with we have the possibility to deploy a [apache/nifi-registry](https://hub.docker.com/r/apache/nifi-registry/) with Helm on a Kubernetes cluster.

I agree threre are pros & cons to deploy the nifi registry in this repo or in a separate repo. 
There is another benefit if we create a seperate chart: in the case you want to deploy Nifi registry with [minifi](https://nifi.apache.org/minifi/index.html). But I agree the automatic part is nice.

If you want to make a first PR, don't hesitate.

**Comment by alexnuttinck** [comment]
#58 implements this feature request.

**Comment by alexnuttinck** [comment]
Added in [0.5.0 release](https://github.com/cetic/helm-nifi/releases/tag/0.5.0).
