### ISSUE TITLE
[cetic/nifi] Test the 1.10 release of nifi

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/helm-nifi#28]
**Is your feature request related to a problem? Please describe.**

Test & Migrate the chart to the last version of nifi:
https://cwiki.apache.org/confluence/display/NIFI/Release+Notes#ReleaseNotes-Version1.10.0

**Describe the solution you'd like**
v1.10 of nifi by default

**Comment by sc7565** [comment]
So, I was able to get 1.10 working with minor changes.

1. Updated Zookeeper chart version - 2.1.1
2. Updated helm-nifi/configs/zookeeper.properties 
- Removed `clientPort=2181`
- Updated `server.1=` --> `server.1=localhost:2888:3888;2181`

Seems to be working fine, in case if someone wants to give a try

As per this - https://cwiki.apache.org/confluence/display/NIFI/Migration+Guidance

**Comment by alexnuttinck** [comment]
Hello @sc7565, thanks for the tips. Nifi 1.10 will be by default in the next release.

**Comment by alexnuttinck** [comment]
merged in [v0.3.0](https://github.com/cetic/helm-nifi/releases/tag/0.3.0).
