### ISSUE TITLE
How  to  run nifi  kubernate as   standalone 

### ISSUE THREAD

**Issue by vikashsingh009** [cetic/helm-nifi#29]
Hi ,
I  have  tested helm-nifi  on  kubernate  and  its  working  only  issue i am  getting   is import  template where template is  of  big processor  when i  dropped  to  convas its  giving  error The specified observer identifier already exists i  have  exported  template  from  standalone  and  import  in  cluster any  idea  solution  how  it  will work.i  also  find  below  link  but   not  useful
http://apache-nifi-users-list.2361937.n4.nabble.com/Error-instantiating-template-on-cluster-The-specified-observer-identifier-already-exists-Reproduced-2-td8452.html#a8471

**Comment by alexnuttinck** [comment]
@vikashsingh009, not sure it is a bug related to the Helm scripts, maybe it is an issue from Nifi ? https://github.com/apache/nifi#getting-help

**Comment by alexnuttinck** [comment]
I close this issue. If there is something else, please create a new issue.
