### ISSUE TITLE
[cetic/nifi] nifi node 4

### ISSUE THREAD

**Issue by devopsdymyr** [cetic/helm-nifi#30]
**Describe the bug**

**Version of Helm and Kubernetes**:
kubernetes 12
**What happened**:
I have tried to install 4 node nifi cluster but getting readyness error.
i have modified in values.yaml file replica count = 4
helm install -n nifi . --namespace nifi
error:
Readiness probe failed: Node not found with CONNECTED state. Full cluster state:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 100.100.0.6...
* TCP_NODELAY set
* Connected to nifi-0.nifi-headless.nifi.svc.cluster.local (100.100.0.6) port 8080 (#0)
> GET /nifi-api/controller/cluster HTTP/1.1
> Host: nifi-0.nifi-headless.nifi.svc.cluster.local:8080
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Tue, 19 Nov 2019 09:44:18 GMT
< X-Frame-Options: SAMEORIGIN
< Content-Security-Policy: frame-ancestors 'self'
< X-XSS-Protection: 1; mode=block
< Content-Type: application/json
< Vary: Accept-Encoding
< Content-Length: 59
< Server: Jetty(9.4.11.v20180605)
<
{ [59 bytes data]
* Curl_http_done: called premature == 0
100    59  100    59    0     0    168      0 --:--:-- --:--:-- --:--:--   169
* Connection #0 to host nifi-0.nifi-headless.nifi.svc.cluster.local left intact
parse error: Invalid numeric literal at line 1, column 5
parse error: Invalid numeric literal at line 1, column 5
  Warning  Unhealthy  91s  kubelet, ip-10-0-56-48.us-west-2.compute.internal  Readiness probe failed: Node not found with CONNECTED state. Full cluster state:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

**What you expected to happen**:
How to set 4 node nifi cluster using helm cetic/nifi.

**Comment by alexnuttinck** [comment]
Hello @devopsdymyr, 

Thanks for your bug request, 

Can you retry to install the helm chart and can you wait a bit more? (I think this the same bug: #8)
I can reproduce your bug on my minikube with 4 nodes. 
It takes 1 or 2 minutes for the Readness probe to succeed. 

The default ReadnessProbe in the statefulset will need to be rework to fix this bug:

```
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 20
          exec:
            command:
            - bash
            - -c
            - |
{{- if .Values.properties.httpsPort }}
              curl -kv \
                --cert ${NIFI_BASE_DIR}/data/cert/admin/crt.pem --cert-type PEM \
                --key ${NIFI_BASE_DIR}/data/cert/admin/key.pem --key-type PEM \
                https://$(hostname -f):8443/nifi-api/controller/cluster > $NIFI_BASE_DIR/data/cluster.state
{{- else }}
              curl -kv \
                http://$(hostname -f):{{ .Values.properties.httpPort }}/nifi-api/controller/cluster > $NIFI_BASE_DIR/data/cluster.state
{{- end }}
              STATUS=$(jq -r ".cluster.nodes[] | select((.address==\"$(hostname -f)\") or .address==\"localhost\") | .status" $NIFI_BASE_DIR/data/cluster.state)

              if [[ ! $STATUS = "CONNECTED" ]]; then
                echo "Node not found with CONNECTED state. Full cluster state:"
                jq . $NIFI_BASE_DIR/data/cluster.state
                exit 1
              fi
```

**Comment by devopsdymyr** [comment]
I have modified initialDelaySeconds: 140 and repilica: 1
helm install -n dev .

![Screenshot from 2019-11-19 22-12-53](https://user-images.githubusercontent.com/41105507/69166819-e1498080-0b19-11ea-8610-79fa8e008359.png)

![Screenshot from 2019-11-19 22-14-20](https://user-images.githubusercontent.com/41105507/69166881-fc1bf500-0b19-11ea-8272-2ee63083ce64.png)
![Screenshot from 2019-11-19 22-15-36](https://user-images.githubusercontent.com/41105507/69166998-2b326680-0b1a-11ea-8657-4ea26c177651.png)
Getting same error ,let me know what should i need to modify
![Screenshot from 2019-11-19 22-17-20](https://user-images.githubusercontent.com/41105507/69167096-62a11300-0b1a-11ea-8463-0b418fe3273b.png)

**Comment by devopsdymyr** [comment]
i have tried with below steps for 4 node cluster.
git clone https://github.com/cetic/helm-nifi.git nifi
cd nifi
helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
helm repo update
helm dep up
helm install --name nifi .
![Screenshot from 2019-11-19 22-29-57](https://user-images.githubusercontent.com/41105507/69168241-57e77d80-0b1c-11ea-8990-6c5d97eda6bc.png)

**Comment by devopsdymyr** [comment]
i have modified to 250 second. but still have same issue 
![Screenshot from 2019-11-19 22-43-34](https://user-images.githubusercontent.com/41105507/69169254-1061f100-0b1e-11ea-86e3-8a0a62e56f7e.png)

**Comment by alexnuttinck** [comment]
@devopsdymyr Can you share logs from the different nifi containers?

```
kubectl logs REALEASE-nifi-X app-log -f
```

**Comment by devopsdymyr** [comment]
i have followed same steps in the github docs only modified replica count 4
git clone https://github.com/cetic/helm-nifi.git nifi
cd nifi
helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
helm repo update
helm dep up
helm install --name nifi .

![Screenshot from 2019-11-20 21-50-51](https://user-images.githubusercontent.com/41105507/69256784-030d3b00-0be0-11ea-80d5-4d5ecfac5c01.png)
please find all logs files
[nifi-2.txt](https://github.com/cetic/helm-nifi/files/3870268/nifi-2.txt)
[nifi-3.txt](https://github.com/cetic/helm-nifi/files/3870269/nifi-3.txt)
[nifi-1.txt](https://github.com/cetic/helm-nifi/files/3870270/nifi-1.txt)

**Comment by devopsdymyr** [comment]
same i have tried in aws kubernetes cluster getting error.
[nif-cluster-2-aws-kubernetes.txt](https://github.com/cetic/helm-nifi/files/3872729/nif-cluster-2-aws-kubernetes.txt)

**Comment by alexnuttinck** [comment]
Hello @devopsdymyr, I did not find anything abnormal. 

Pod nifi 1 took the lead, pod nifi 3 was well connected to nifi 1. (We can see that all these pods are ready)
Pod nifi 2 seems not yet to be connected to the others.

Your time to launch all the pods seems nevertheless extremely long. Has your Kubernetes cluster enough computing resources?

**Comment by devopsdymyr** [comment]
Let me tell you entire steps executed from new cluster.
kops create cluster --name=testing --state=s3://<mybucket> --zones=us-east-1a --node-count=3 --node-size=t2.medium --master-size=t2.small --dns-zone=dymyr.com
kops update cluster testing --state=s3://<mybucket> --yes
watch -n 1 kubectl  get node
cat << EOF | kubectl create -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
EOF

helm init --service-account tiller

i have followed same steps in the github docs only modified replica count 4
git clone https://github.com/cetic/helm-nifi.git nifi
cd nifi
helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
helm repo update
helm dep up
helm install --name nifi .

Now it started working but not idea what is the difference because i have followed same steps from day1 of the this bug,,,I need document reference for take backup .Thanks for your support
