### ISSUE TITLE
[cetic/nifi] Set up Nifi with LDAP/HTTPS

### ISSUE THREAD

**Issue by tuanvuvo** [cetic/helm-nifi#35]
**Describe the bug**
Pls help me for set up LDAP/HTTPS for Nifi in Kube

**Version of Helm and Kubernetes**:
Helm: 2.16
Kube: 1.16

**What happened**:
I tried to set up my nifi in Kube under LDAP and HTTPS but can't worked. Can you help us?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by sc7565** [comment]
Same here, it seems confusing .. few pointers would be really helpful

**Comment by banzo** [comment]
This is not yet implemented in the chart, but it is in [FADI](https://github.com/cetic/fadi) roadmap so stay tuned! (or do not hesitate to make a PR if you manage to get it working before then)

**Comment by alexnuttinck** [comment]
WIP here: #70

**Comment by alexnuttinck** [comment]
Done in the last PR, available in the 0.6.1 release.
