### ISSUE TITLE
[cetic/nifi] kubernetes node update nifi error

### ISSUE THREAD

**Issue by devopsdymyr** [cetic/helm-nifi#38]
**Describe the bug**
Using kops i have updated my instance size of large 
![Screenshot from 2019-12-31 04-10-56](https://user-images.githubusercontent.com/41105507/71603586-96447380-2b83-11ea-9a43-981ad53bab5c.png)
Before update my cluster nifi cluster is working fine but after update my cluster getting error
![Screenshot from 2019-12-31 04-12-16](https://user-images.githubusercontent.com/41105507/71603625-c724a880-2b83-11ea-84f3-a0d2583471ff.png)
![Screenshot from 2019-12-31 04-16-14](https://user-images.githubusercontent.com/41105507/71603725-5205a300-2b84-11ea-8733-43ac6526c0c9.png)

Pod describe is montioned on the txt file
[nifi-1-describce.txt](https://github.com/cetic/helm-nifi/files/4011338/nifi-1-describce.txt)

**Version of Helm and Kubernetes**:
helm version --short
Client: v2.16.1+gbbdfe5e
Server: v2.16.1+gbbdfe5e

**What happened**:
Nifi custer is not connecting to nodes

**What you expected to happen**:
After update cluster should work all nifi data and cluster in working state

**How to reproduce it** (as minimally and precisely as possible):
kops install new cluster
install helm
install nifi cluster using helm as per installation documents with 2 node cluster
Nifi exposed using nginx ingress
kops update your new node size
https://github.com/kubernetes/kops/blob/master/docs/cli/kops_edit_cluster.md

Once everything updated check your ingress will have issue

**Anything else we need to know**:

@ebcFlagman @octopyth @mgoeminne @jdesroch @fzalila

**Comment by fzalila** [comment]
@alexnuttinck @AyadiAmen @banzo

**Comment by devopsdymyr** [comment]
Any suggestion?
