### ISSUE TITLE
[cetic/nifi] issue title annotations for basic auth

### ISSUE THREAD

**Issue by devopsdymyr** [cetic/helm-nifi#42]
**Describe the bug**
I have tried to create nifi basic auth using nginx but littlebit confusion on the annotations.
Anyone give me some sample for the annotations passwd for basic auth
**Version of Helm and Kubernetes**:
 helm version --short
Client: v2.16.1+gbbdfe5e
Server: v2.16.1+gbbdfe5e

k8s: v1.14.8

**What happened**:
HOw to added basic auth from helm chart
cat secrets-auth.yaml
https://github.com/cetic/helm-nifi/blob/master/templates/secrets-auth.yaml

How to pass annotation in ingress values.yaml
ingress:
  enabled: true
  annotations: {}
  tls: []
  hosts: []
  path: /

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by alexnuttinck** [comment]
@devopsdymyr basic auth secrets should not be done created in this Chart, so I will remove it. You need to setup your Ingress Controller (Nginx, Traefik, ...) for that, and pass the good annotations. Please, see their documentation for that. For instance, https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/basic
