### ISSUE TITLE
LoadBalancer  ip  specifi  in value.yml  not  reflecting in  svc

### ISSUE THREAD

**Issue by vikashsingh009** [cetic/helm-nifi#43]
Hello,
I  have  use  azure  aks  to  deploy  nifi ,i  have  chnaged below  line in value.yml
# headless service
headless:
  type: ClusterIP
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

# ui service
service:
  type: LoadBalancer
  enabled: true
  httpPort: 80
  httpsPort: 443
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-resource-group: mc_visurdremio_dremio_canadacentral
   loadBalancerIP: 52.228.103.111
  ## Load Balancer sources
  ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24

##
ingress:
  enabled: false
  annotations: {}
  tls: []
  hosts: []
  path: /

after  that  i  have  restarted  the helm ,this  ip  i  have  created  static and  trying  to  assign  but its  assign  some  random  IP please  guide me  how  to  sepecify  own  ip  address  as  LB
![Screenshot_4](https://user-images.githubusercontent.com/7962189/71952685-92f55b80-3205-11ea-9bdf-e331f5a45352.png)
![Screenshot_5](https://user-images.githubusercontent.com/7962189/71952694-97217900-3205-11ea-9811-97783ce7c28b.png)

**Comment by alexnuttinck** [comment]
@vikashsingh009 you have made an indentation error for the `loadBalancerIP`.

**Comment by vikashsingh009** [comment]
@alexnuttinck i  have  tried all  possiblity  like  put  only  one  entry  in  service.yml but  still  i  am  not  getting  LB  ip  it always  have  random here is  my  value.yml  changes

value.yml
------------
service:
  type: LoadBalancer
  enabled: true
  httpPort: 80
  httpsPort: 443
  annotations:
   loadBalancerIP: 52.228.103.111
 ingress:
  enabled: false
  annotations: {}
  tls: []
  hosts: []
  path: /

service.yml
---------
 ---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: 52.228.103.111
  ports:
{{- if .Values.properties.clusterSecure }}
    - port: {{ .Values.service.httpsPort }}
      name: https
      targetPort: {{ .Values.httpsPort }}
{{- else }}
    - port: {{ .Values.service.httpPort }}
      name: http
      targetPort: {{ .Values.properties.httpPort }}
{{- end }}
  selector:
    app: {{ template "apache-nifi.name" . }}
    release: {{ .Release.Name }}

while  describing  svc  i  am  not  getting  any  error now 

![image](https://user-images.githubusercontent.com/7962189/71986893-3e78cd00-3253-11ea-9a1e-4a8cb6d61418.png)

**Comment by alexnuttinck** [comment]
Perhaps it is related to aks? Personally, I have no issue on gke for that point. Maybe, try to find find some examples for aks? I close this issue as I don't think it's an issue related to the Chart.
