### ISSUE TITLE
Escape dot sequences wont work in ingress.annotations

### ISSUE THREAD

**Issue by shrivastavshubham34** [cetic/helm-nifi#50]
**Describe the bug**
Helm chart runs successfully without showing any errors, but ingress is not getting created after adding below command
```bash
 helm install random-nifi cetic/nifi --set persistence.enabled=true --set service.type=NodePort --set ingress.hosts={nifi.nonprod.random.com} --set ingress.annotations."kubernetes\.io/ingress\.class"=alb
```
I can run this successfully by modifying values.yaml and running helm locally, but my scenario requires me to run this along with --set parameter on the command line which doesn't work.

**Version of Helm and Kubernetes**:
Helm v3.1.2
K8s v1.14

**Comment by alexnuttinck** [comment]
Hello @shrivastavshubham34,

You can override default values in a separate file and [by using the -f <file.yaml> option](https://helm.sh/docs/chart_best_practices/values/#consider-how-users-will-use-your-values). I think it will be easier for you.

Install the chart like this:
```
helm install random-nifi cetic/nifi -f values.yaml
```

and you alsoneed to enable the ingress:

```
ingress:
  enabled: true

**Comment by ellisio** [comment]
If anyone stumbles on this issue from Google searching, the reason is you are not double escaping.

```
--set ingress.annotations."kubernetes\.io/ingress\.class"=alb
```

Needs to be:

```
--set ingress.annotations."kubernetes\\.io/ingress\\.class"=alb
```

**Comment by zffocussss** [comment]
> If anyone stumbles on this issue from Google searching, the reason is you are not double escaping.
> 
> ```
> --set ingress.annotations."kubernetes\.io/ingress\.class"=alb
> ```
> 
> Needs to be:
> 
> ```
> --set ingress.annotations."kubernetes\\.io/ingress\\.class"=alb
> ```

you save me
