### ISSUE TITLE
[cetic/nifi] helm lint fails

### ISSUE THREAD

**Issue by gisaf16** [cetic/helm-nifi#51]
**Describe the bug**
Helm lint fails on chart, apiVersion is required (missing in Chart.yaml)

**Version of Helm and Kubernetes**:
Helm v3.0.3, Go v1.13.6

**What happened**:

**What you expected to happen**:
helm lint to PASS

**How to reproduce it** (as minimally and precisely as possible):
navigate to NiFi folder and run "helm lint ." in the terminal

**Anything else we need to know**:

**Comment by alexnuttinck** [comment]
Hello @gisaf16,

Thanks for this bug report. It will be fixed when we will upgrade this chart to Helm v3 by:

* moving dependencies.yaml into Chart.yaml.
* adding the apiVersion.

You can nevertheless run this Helm chart with v3.

**Comment by alexnuttinck** [comment]
@gisaf16 it is fixed in 0.4.0.
