### ISSUE TITLE
[cetic/nifi] define custom initContainers in values

### ISSUE THREAD

**Issue by stoetti** [cetic/helm-nifi#53]
**Is your feature request related to a problem? Please describe.**
We would like to instantiate nifi including a custom processor and a pre-defined flow but without having to create a separate nifi-image or helm-chart.

**Describe the solution you'd like**
If the chart could provide a value that makes it possible to define a custom init-container this could give us the possibility to copy the additional files (nar and flow.xml.gz) to the nifi-container itself by using the same volumes.
This adds the possibility to define extra volumeMounts as well.

**Describe alternatives you've considered**
The current solution that is provided via the docs, using postStart-hook and download the files will not work for us as we have the need to run the chart in some highly secured environment without connection to the outside world. It is easier to bring some docker-image containing the files into this secure environment than providing file downloads.

**Additional context**
Here is a chart I found that provides the mechnisms described above. https://github.com/fluxcd/flux/tree/master/chart/flux

**Comment by stoetti** [comment]
A second possible solution for the specific case would be to share a mount between two containers. This implies the feature request to add a custom container to the nifi-pod.

Documentation about shared volumes - https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/

**Comment by alexnuttinck** [comment]
@stoetti your feature request makes senses, thanks! I will look into your PR asap.

**Comment by alexnuttinck** [comment]
@stoetti merged in 0.3.4 & 0.4.0
 Thanks!
