### ISSUE TITLE
[cetic/nifi] Providing Private Keys to Cluster

### ISSUE THREAD

**Issue by iwarp** [cetic/helm-nifi#64]
**Is your feature request related to a problem? Please describe.**
NiFi doesn't have any secure key storage and relies on file system for example the SFTP private key file references a local path. This isn't a great solution when you are running a cluster as nodes can be missed and more importantly when its on Kubernetes how do we inject these into the container. 

**Describe the solution you'd like**
Ideally a if there was a configuration parameter that creates a number of ConfigMap to present these into the cluster as files on the filesystem that NiFi can access.

Thanks!

**Comment by alexnuttinck** [comment]
Hello @iwarp,

I think it's already implemented, if I understand well your feature request. See https://github.com/cetic/helm-nifi/blob/master/values.yaml#L42
