### ISSUE TITLE
[cetic/nifi] Add annotation support for processors port, to make prometheus scrape autodiscovery possible

### ISSUE THREAD

**Issue by appunni-dishq** [cetic/helm-nifi#65]
Adding support for annotations let's us use the latest feature of PrometheusReportingTask from NIfi and let prometheus automatically scrape it.

**Comment by novakov-alexey** [comment]
@appunni-dishq are you working on this? I also need this feature, so that I can try to implement it.

**Comment by alexnuttinck** [comment]
Added in [0.4.4 release](https://github.com/cetic/helm-nifi/releases/tag/0.4.4).
