### ISSUE TITLE
Ingress toute to headless service instead of LoadBalancer

### ISSUE THREAD

**Issue by ebcFlagman** [cetic/helm-nifi#7]
I've the following configuration:
`persistence:
  enabled: true
  storageClass: managed-azuredisk-standard-lrs
service:
  loadBalancer:
    enabled: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  path: /nifi/(.*)
  hosts:
    - foo.bar
  tls:
    - secretName: tls-secret
      hosts:
        - foo.bar
zookeeper:
  enabled: false
  url: cl-zookeeper.ingestion`

With this config the Ingress-Service points to the Deploy-Name instead of the headless-Service.
Can this be changed or should I configure the LoadBalancer type to ClusterIP?

**Comment by alexnuttinck** [comment]
Hello @ebcFlagman,
By enabling the LoadBalancer like this, it should work:

```yaml
service:
  loadBalancer:
    enabled: true
    type: ClusterIP
```

I know it is not really intuitive and it should be rework.

**Comment by ebcFlagman** [comment]
Thx, I've done it like that and it worked for me
