### ISSUE TITLE
Are Zookeeper and the Nifi registry mandatory?

### ISSUE THREAD

**Issue by abhi7788** [cetic/helm-nifi#75]
**Describe the bug**
I will not categorize my issue as bug, it is more of a kind request for more information/clarification I am seeking. As per the values.yaml documentation for the sections zookeeper it is mentioned that if the value is true then we have to deploy the zookeeper chart incase the value is false then we have to provide zookeeper url and port; Is it mandatory to run zookeeper with Apache Nifi or we can setup Nifi without zookeeper too?

Similarly for Nifi registry too, do we need to setup Nifi registry or we can setup value as false and by pass setting up Nifi-registry totally. 

I was not sure about both the above components therefore posted this question...Looking forward for assistance on this.

Thanks

**Comment by alexnuttinck** [comment]
Hello @abhi7788,

Zookeeper is mandatory.
Nifi registry should not be mandatory, but I need to check there is no problem when it is disabled (as it is a quite recent feature to this chart). And I need to modify the README.md to be clear.

**Comment by abhi7788** [comment]
Thanks @alexnuttinck for the reply. Since Zookeeper is mandatory therefore I am assuming that we do have the capability to run a distributed Nifi system on Kubernetes also. That means lets say if i have two pods running for the Nifi and i start a data pipeline, the execution will happen on both the pods. Correct me if I am wrong here.

**Comment by alexnuttinck** [comment]
@abhi7788 exact :)

**Comment by abhi7788** [comment]
Awesome...Thanks alot for all this information. Since i was occupied with some other urgent things therefore did not got much time to implement and test this out. Hopefully i will start on this by next week. In the meanwhile I am good to close the issue. Will let you know incase if I run into some thing else....

Thanks!!!
