### ISSUE TITLE
Support custom processors

### ISSUE THREAD

**Issue by banzo** [cetic/helm-nifi#78]
Feature request: ability to add a [custom processor](https://www.tutorialspoint.com/apache_nifi/apache_nifi_custom_processor.htm) to Nifi.

We would have a way to provide the `.nar` files for the custom processors to the chart so that those files are available in the `$ NIFI_HOME/lib` folder.

Using postaction as we did for the PostgreSQL driver is not applicable since the processors need to be available at Nifi startup, so maybe we could have a new volume for the `$NIFI_HOME/lib` folder.

**Comment by alexnuttinck** [comment]
@banzo you can use extraVolumes for that: https://github.com/cetic/helm-nifi/blob/master/values.yaml#L229
