### ISSUE TITLE
[cetic/nifi] Support different service account

### ISSUE THREAD

**Issue by nwalens** [cetic/helm-nifi#84]
**Is your feature request related to a problem? Please describe.**
In Openshift containers cannot run with a set fsGroup or runAsUser that is not specified/permitted in the range assigned to the namespace/project.

As in this helm chart and docker image the user has to be set to a specific value, one must then permit the statefulset to use the 'anyuid' security context/sccm.
SCCM are based on service accounts so if I want to permit a statefulset to start as any kid, the service account set for that statefulset has to be assigned to a specific scc.
More can be found [here](https://docs.openshift.com/container-platform/4.5/security/container_security/security-platform.html#security-deployment-sccs_security-platform) and [here](https://docs.openshift.com/container-platform/4.5/authentication/managing-security-context-constraints.html#managing-pod-security-policies)

If the chart supports to define a service account, it would make it easy to use something like kustomize to define a security context that allows the container to use any user id or a specific one if needed.

**Describe the solution you'd like**
The idea is to have an option like:
`sts.serviceAccountName:` <service account>

This way one can define a specific service account for the nigh statefulset.

**Describe alternatives you've considered**
Right now my only alternatives are to either clone the chart and add the option or run after helm template.

**Comment by alexnuttinck** [comment]
Thanks for your PR @nwalens. I close this issue.
