### ISSUE TITLE
helm version issue

### ISSUE THREAD

**Issue by balajir24** [cetic/helm-nifi#87]
Hi,

We have configured the nifi (chart 0.5.1) with helm v2.16.10. now it is throwing error when try to upgrade values.

```
Error: apiVersion 'v2' is not valid. The value must be "v1"
```

It is expecting helm v3. please help on this.

Thanks,
Balaji.R

**Comment by alexnuttinck** [comment]
Yes, you should upgrade your helm client to v3: https://helm.sh/docs/intro/install/#from-script

Helm v2 will be soon deprecated: https://helm.sh/blog/helm-v2-deprecation-timeline/
